apiVersion: engine.kube.ci/v1alpha1
kind: Workflow
metadata:
  name: sample-workflow
  namespace: demo
spec:
  serviceAccount: default
  executionOrder: DAG
  allowManualTrigger: true
  nodeSelector:
    kubernetes.io/hostname: minikube
  steps:
  - name: step-01
    image: alpine
    commands:
    - sh
    args:
    - -c
    - date; sleep 5s; date
  - name: step-02
    image: alpine
    commands:
    - sh
    args:
    - -c
    - date; sleep 5s; date
    requires:
    - step-01
  - name: step-03
    image: alpine
    commands:
    - sh
    args:
    - -c
    - date; sleep 5s; date
    requires:
    - step-01
  - name: step-04
    image: alpine
    commands:
    - sh
    args:
    - -c
    - date; sleep 5s; date
    requires:
    - step-03
  - name: step-05
    image: alpine
    commands:
    - sh
    args:
    - -c
    - date; sleep 5s; date
    requires:
    - step-04
  - name: step-06
    image: alpine
    commands:
    - sh
    args:
    - -c
    - date; sleep 5s; date
    requires:
    - step-04

# dependency: 01 | 02 03 | 04 | 05 06