apiVersion: engine.kube.ci/v1alpha1
kind: Workflow
metadata:
  name: sample-workflow
  namespace: demo
spec:
  serviceAccount: wf-sa
  executionOrder: Serial
  allowManualTrigger: true
  steps:
  - name: clone
    image: alpine/git
    commands:
    - sh
    args:
    - -c
    - git clone https://github.com/kube-ci/kubeci-gpig .
  - name: build-and-push
    image: gcr.io/kaniko-project/executor
    args:
    - --dockerfile=/kubeci/workspace/Dockerfile
    - --context=/kubeci/workspace
    - --destination=index.docker.io/kubeci/kubeci-gpig:kaniko