apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: demo
  name: wf-sa
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: wf-role
rules:
- apiGroups: ["git.kube.ci"]
  resources: ["pullrequests"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["secrets", "configmaps"]
  verbs: ["get", "list", "watch", "create"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: wf-role-binding
  namespace: demo
subjects:
- kind: ServiceAccount
  namespace: demo
  name: wf-sa
roleRef:
  kind: ClusterRole
  name: wf-role
  apiGroup: rbac.authorization.k8s.io
---
# operator needs same permissions but for all namespaces
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: wf-role-binding
subjects:
- kind: ServiceAccount
  namespace: kube-system
  name: kubeci-engine
roleRef:
  kind: ClusterRole
  name: wf-role
  apiGroup: rbac.authorization.k8s.io
