apiVersion: engine.kube.ci/v1alpha1
kind: Workflow
metadata:
  name: sample-workflow
  namespace: demo
spec:
  serviceAccount: default
  executionOrder: Serial
  allowManualTrigger: true
  steps:
  - name: step-one
    image: alpine
    commands:
    - touch
    args:
    - /path-one/file-01
    volumeMounts: # explicit volume mounts
    - name: sample-volume
      mountPath: /path-one
  - name: step-two
    image: alpine
    commands:
    - ls
    args:
    - /path-two
    volumeMounts: # explicit volume mounts
    - name: sample-volume
      mountPath: /path-two
  volumes: # explicit volumes
  - name: sample-volume
    hostPath:
      path: /tmp/sample-volume
      type: DirectoryOrCreate