apiVersion: engine.kube.ci/v1alpha1
kind: Workflow
metadata:
  name: sample-workflow
  namespace: demo
spec:
  serviceAccount: wf-sa
  executionOrder: DAG
  allowManualTrigger: true
  volumes:
  - name: dind-storage
    emptyDir: {}
  envVar:
  - name: DOCKER_HOST
    value: tcp://localhost:2375
  steps:
  - name: clone
    image: alpine/git
    commands:
    - sh
    args:
    - -c
    - git clone https://github.com/kube-ci/kubeci-gpig .
  - name: dind-daemon
    image: docker:18.09-dind
    securityContext:
      privileged: true
      procMount: Default
    volumeMounts:
    - name: dind-storage
      mountPath: /var/lib/docker
    requires:
    - clone
  - name: build-and-push
    image: docker:18.09
    commands:
    - sh
    args:
    - -c
    - docker build -t kubeci/kubeci-gpig:dind .; docker push kubeci/kubeci-gpig:dind
    requires:
    - clone